[package]
name = "drivers"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
embedded-hal.workspace = true

[features]
default = ["std"]
std = []